# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [25]:
import numpy as np

In [26]:
# ejercicio 1 
a1 = np.array([1, 2, 3, 4])
print("1:", np.all(a1 != 0))


1: True


In [27]:
# ejercicio 2
a2 = np.array([0, 0, 2, 0])
print("2:", np.any(a2 != 0))

2: True


In [28]:
# ejercicio 3
a3 = np.array([1, 2, np.nan, np.inf])
print("3 - NaN:", np.isnan(a3).any())


3 - NaN: True


In [29]:
# ejercicio 4
a4 = np.array([1, 2, np.inf])
print("4:", np.isinf(a4).any())


4: True


In [30]:
# ejercicio 5
a5 = np.array([1, np.nan, 3])
print("5:", np.isnan(a5).any())



5: True


In [31]:
# ejercicio 6
a6 = np.array([1, 3, 5])
b6 = np.array([2, 3, 4])
print("6 - Mayor:", a6 > b6)       
print("6 - Mayor o igual:", a6 >= b6) 
print("6 - Menor:", a6 < b6)       
print("6 - Menor o igual:", a6 <= b6)


6 - Mayor: [False False  True]
6 - Mayor o igual: [False  True  True]
6 - Menor: [ True False False]
6 - Menor o igual: [ True  True False]


In [32]:
# ejercicio 7
a7 = np.array([1, 7, 13, 105])
print("7:", a7.nbytes, "bytes")


7: 32 bytes


In [33]:
# ejercicio 8
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)
print("8 - Ceros:", zeros)
print("8 - Unos:", ones)
print("8 - Cincos:", fives)


8 - Ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8 - Unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
8 - Cincos: [5 5 5 5 5 5 5 5 5 5]


In [34]:
# ejercicio 9
a9 = np.arange(30, 71)
print("9:", a9)


9: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [35]:
# ejercicio 10
a10 = np.arange(30, 71, 2)
print("10:", a10)



10: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [36]:
# ejercicio 11
identity = np.eye(3)
print("11:\n", identity)



11:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# ejercicio 12
rand_num = np.random.rand()
print("12:", rand_num)


12: 0.31369797426335744


In [38]:
# ejercicio 13
normal_array = np.random.randn(15)
print("13:", normal_array)



13: [ 0.24351883 -1.31048438 -0.36285632 -2.12565417 -1.20380345  1.90601292
 -0.50966258 -1.20577434  0.20611739  3.43856092 -0.74881187 -0.58086438
 -0.06716755  0.34437468 -1.32910329]


In [39]:
# ejercicio 14
a14 = np.arange(15, 56)
print("14:", a14[1:-1])



14: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [40]:
# ejercicio 15
a15 = np.linspace(5, 50, 10)
print("15:", a15)



15: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [41]:
# ejercicio 16
a16 = np.arange(0, 21)
a16[(a16 >= 9) & (a16 <= 15)] *= -1
print("16:", a16)


16: [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [42]:
# ejercicio 17
a17 = np.array([1, 2, 3])
print("17:", a17.tolist())


17: [1, 2, 3]


In [43]:
# ejercicio 18
l18 = [1, 2, 3]
a18 = np.array(l18)
print("18:", a18)



18: [1 2 3]


In [44]:
# ejercicio 19
m19 = np.array([[1, 2], [3, 4]])
pares = m19 % 2 == 0
print("19:\n", pares)



19:
 [[False  True]
 [False  True]]


In [45]:
# ejercicio 20
m20 = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m20.shape
print("20 - Filas:", filas)
print("20 - Columnas:", columnas)




20 - Filas: 2
20 - Columnas: 3
