In [1]:
import numpy as np

In [2]:
lista = [0,1,2,3,4]
array_1d = np.array(lista)

#Checamos el tipo de dato de array_id
type(array_1d)

numpy.ndarray

In [3]:
#contenido del array
array_1d

array([0, 1, 2, 3, 4])

In [4]:
lista = [0,1,2,3,4]
array_1d = np.array(lista)
array_1d + 2

array([2, 3, 4, 5, 6])

In [5]:
def multiplicar_matrices(A, B):
    # obtener dimensiones
    filas_A = len(A)
    cols_A = len(A[0])
    filas_B = len(B)
    cols_B = len(B[0])

    # checar si se pueden multiplicar A y B
    if cols_A != filas_B:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")

    # Inicializar una matriz vacía con ceros
    matriz_resultado = []
    for _ in range(filas_A):
        fila = []
        for _ in range(cols_B):
            fila.append(0)
        matriz_resultado.append(fila)

    # realizar multiplicación
    for i in range(filas_A):
        for j in range(cols_B):
            for k in range(cols_A):
                matriz_resultado[i][j] += A[i][k] * B[k][j]

    return matriz_resultado

# Ejemplo
A = [
    [1, 2, 3],
    [4, 5, 6]
]
B = [
    [7, 8],
    [9, 10],
    [11, 12]
]
C = multiplicar_matrices(A, B)
print(C)

[[58, 64], [139, 154]]


In [6]:
import random

def generar_matriz_aleatoria(N):
    matriz = []
    for i in range(N):
        fila = []
        for j in range(N):
            fila.append(random.randint(1, 10))
        matriz.append(fila)
    return matriz

# Ejemplo de uso
N = 5
matriz_aleatoria = generar_matriz_aleatoria(N)
for fila in matriz_aleatoria:
    print(fila)

[5, 4, 5, 6, 4]
[4, 7, 1, 4, 5]
[4, 6, 3, 6, 10]
[4, 3, 5, 6, 2]
[7, 3, 7, 10, 5]


In [7]:
def imprimir_matriz(matriz):
    for fila in matriz:
        fila_formateada = ' '.join(f'{elemento:2}' for elemento in fila)
        print(fila_formateada)

In [8]:
print("Matríz de 5x5:")
m_5 = generar_matriz_aleatoria(5)
imprimir_matriz(m_5)
print("====================")
print("Matríz de 10x10:")
m_10 = generar_matriz_aleatoria(10)
imprimir_matriz(m_10)
print("====================")
print("Matríz de 20x20:")
m_20 = generar_matriz_aleatoria(20)
imprimir_matriz(m_20)
print("====================")
m_100 = generar_matriz_aleatoria(100)

Matríz de 5x5:
 5  5  5  3  6
 7  6  6  4  1
10  2  8  7  2
 9  1  7  9  5
 3  7  3 10  7
Matríz de 10x10:
 1  6  5  1  3  5  2  7  4  7
 5  8  7  3  3  1 10  1  3  9
 1  7  4  9  2  8  8  9  1  1
10  8  5  7  3  5 10  9  5 10
 6  1  3  3  8  3  6  5 10  4
 5  6  4  7  3  2  8 10  6  9
 7  5  9  1  3  6  1  1  9  3
 8  6  1  5  1  7  8  3 10  3
 7  3  4  6 10  6  9 10  8  6
 6  1  1 10  3  8  8 10  4  9
Matríz de 20x20:
 3  4  4  2  2  7  4  5  1  9  6  4  1  5  8  3  2  4  6  2
 1  3  8  8  4 10  6 10  4  1  3  8  4  6  9  5  2  7 10  4
 7  2  9  6  4  1  6  2  9  3  6  1  4  5  3  1  9  3  6  1
 1  9  2  3  3  2  8  3  5  4  9  6  9  2  1  3  6  7  7  9
 3  3  5  2  4  6  9 10  8  7  3  6  9  1  4  1  7 10  4  3
 4  5  8 10  9  5  3  8  4  8  1  1  6  7  2  5  9  8  3 10
 3  2  2  4  8  7  9  4 10  6  7  1  7  6  5  8 10  7  2  9
 2  9  6  4  4 10  5  6  5  1  5  8  8  7  5  9  1  4  6  9
 8  8 10  3  3  1  9  7  8  1  1  1  9  8  5  9  8  8 10 10
 2  1  8  3  3  9  9 10  3  3  4  5 

In [9]:
import time

In [10]:
start = time.time()
# ejecutar código
end = time.time()
tiempo = round(end - start, 5)
print(f"La ejecución tardó {tiempo} seg.")

La ejecución tardó 0.00012 seg.


In [11]:
start = time.time()
multiplicar_matrices(m_5, m_5)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 5x5 tardó {tiempo} seg.")

Multiplicar dos matrices de 5x5 tardó 0.00024509429931640625 seg.


In [12]:
start = time.time()
multiplicar_matrices(m_100, m_100)
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 1000x1000 tardó {tiempo} seg.")

Multiplicar dos matrices de 1000x1000 tardó 0.4214053153991699 seg.


In [13]:
print("Matríz de 5x5:")
m_5 = generar_matriz_aleatoria(5)
imprimir_matriz(m_5)
print("====================")
print("Matríz de 10x10:")
m_10 = generar_matriz_aleatoria(10)
imprimir_matriz(m_10)
print("====================")
print("Matríz de 20x20:")
m_20 = generar_matriz_aleatoria(20)
imprimir_matriz(m_20)
print("====================")
m_100 = generar_matriz_aleatoria(100)

Matríz de 5x5:
 1  3  6  3  7
 1  2 10  1  7
 2 10  3  8  9
 4  2  2  3  7
 6 10  8  5  5
Matríz de 10x10:
 8  1  8  9  7  6  4  7  9 10
 4  1  7  1 10 10  6  9  1  2
 3  9  2  8  3  5  6 10  5  5
 1  7  6  4  1  9  3  5  4  5
 1  6  6  7  6  1  6  2  7  2
 8  4  1  3  6  4  2  3  9  8
10  5  6  7  9  1  8  8  2  8
 1  6 10  8  3  3 10 10  1  3
 5  9  7  5  2  7  6 10  2  4
 9  2  6  9  9  6  6  7  1  6
Matríz de 20x20:
 6 10  9  1  8  9  9  8  8  7  8  8  9  6  3  5  8  5  8  2
 5  5  3  9  2  2  8  1  3  5  8  2  3  2  2  7  2  2  2 10
 5  6  9  7 10  2  9  1  9  5  2  1  3  9  3  8  9 10  1  2
10  2  7 10  6  7 10  9 10  1 10  3  4  9  7  1  2  4 10 10
 3  5  6  4  3  8  7  2  1  2 10  5  2  2  4  9  6  4  3  5
 2  6  3  9  8  1  6 10 10  1  1  2  7  9  1  4  5 10  3  8
 9 10 10 10 10  6  3  6  2  5  8  7 10  3 10  9  1  9  2  4
 3  5  6  2  6  5  6  9  6  5  6  6  8  2  8  1  1  2  4  4
 3  4  7  2  2  1  5  9  1  6  2  9 10  3  5  3 10  7  3  7
 3  3  2  3  9  5  4  8  4  4  4  6 

In [14]:
print("====================")
m_100 = generar_matriz_aleatoria(100)

In [15]:
def generar_matriz_aleatoria_numpy(N):
    return np.random.randint(1, 10, size=(N, N))

In [16]:
m_1000 = generar_matriz_aleatoria_numpy(1000)

In [17]:
start = time.time()
np.dot(m_1000, m_1000)
# o bien, m_1000 @ m_1000
end = time.time()
tiempo = end - start
print(f"Multiplicar dos matrices de 1000x1000 con Numpy tardó {tiempo} seg.")

Multiplicar dos matrices de 1000x1000 con Numpy tardó 2.834904193878174 seg.


In [18]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])